steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA', '-f', 'Dockerfile', '.']
  id: 'build'
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA']
  id: 'push'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
  args: [
    'gcloud', 'run', 'deploy', '$_SERVICE_NAME',
    '--image', '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA',
    '--platform', 'managed',
    '--region', 'europe-west1',
    '--port', '8080',
    '--timeout', '300',  # Extend timeout to 5 minutes
    '--set-env-vars', 'GCS_BUCKET_NAME=$_GCS_BUCKET_NAME'
  ]
  id: 'deploy'
images:
- '$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA'
options:
  logging: CLOUD_LOGGING_ONLY